// Copyright (c) Microsoft Corporation.
// All rights reserved.
//
// This code is licensed under the MIT License.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files(the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and / or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions :
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

#pragma once

extern NSString *const AD_TELEMETRY_EVENT_API_EVENT;
extern NSString *const AD_TELEMETRY_EVENT_TOKEN_GRANT;
extern NSString *const AD_TELEMETRY_EVENT_AUTHORITY_VALIDATION;
extern NSString *const AD_TELEMETRY_EVENT_ACQUIRE_TOKEN_SILENT;
extern NSString *const AD_TELEMETRY_EVENT_LAUNCH_BROKER;
extern NSString *const AD_TELEMETRY_EVENT_AUTHORIZATION_CODE;
extern NSString *const AD_TELEMETRY_EVENT_TOKEN_CACHE_LOOKUP;
extern NSString *const AD_TELEMETRY_EVENT_TOKEN_CACHE_WRITE;
extern NSString *const AD_TELEMETRY_EVENT_TOKEN_CACHE_DELETE;
extern NSString *const AD_TELEMETRY_EVENT_UI_EVENT;
extern NSString *const AD_TELEMETRY_EVENT_HTTP_REQUEST;

extern NSString *const AD_TELEMETRY_PROPERTY_NAME_AUTHORITY_TYPE;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_AUTHORITY_VALIDATION_STATUS;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_EXTENDED_EXPIRES_ON_SETTING;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_PROMPT_BEHAVIOR;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_RESULT_STATUS;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_IDP;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_TENANT_ID;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_USER_ID;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_START_TIME;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_END_TIME;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_RESPONSE_TIME;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_DEVICE_ID;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_APPLICATION_NAME;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_APPLICATION_VERSION;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_LOGIN_HINT;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_NTLM_HANDLED;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_UI_EVENT_COUNT;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_BROKER_APP;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_BROKER_VERSION;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_BROKER_PROTOCOL_VERSION;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_BROKER_APP_USED;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_CLIENT_ID;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_HTTP_EVENT_COUNT;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_CACHE_EVENT_COUNT;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_API_ID;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_TOKEN_TYPE;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_USER_CANCEL;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_IS_RT;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_IS_MRRT;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_IS_FRT;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_RT_STATUS;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_MRRT_STATUS;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_FRT_STATUS;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_IS_SUCCESSFUL;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_USER_CANCEL;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_CORRELATION_ID;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_CLIENT_ID;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_IS_EXTENED_LIFE_TIME_TOKEN;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_ERROR_CODE;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_PROTOCOL_CODE;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_ERROR_DESCRIPTION;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_ERROR_DOMAIN;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_HTTP_METHOD;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_HTTP_PATH;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_HTTP_REQUEST_ID_HEADER;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_HTTP_RESPONSE_CODE;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_OAUTH_ERROR_CODE;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_HTTP_RESPONSE_METHOD;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_REQUEST_QUERY_PARAMS;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_USER_AGENT;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_HTTP_ERROR_DOMAIN;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_AUTHORITY;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_GRANT_TYPE;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_API_STATUS;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_EVENT_NAME;
extern NSString *const AD_TELEMETRY_PROPERTY_NAME_REQUEST_ID;

extern NSString *const AD_TELEMETRY_PROPERTY_VALUE_YES;
extern NSString *const AD_TELEMETRY_PROPERTY_VALUE_NO;
extern NSString *const AD_TELEMETRY_PROPERTY_VALUE_TRIED;
extern NSString *const AD_TELEMETRY_PROPERTY_VALUE_NOT_FOUND;
extern NSString *const AD_TELEMETRY_PROPERTY_VALUE_ACCESS_TOKEN;
extern NSString *const AD_TELEMETRY_PROPERTY_VALUE_MULTI_RESOURCE_REFRESH_TOKEN;
extern NSString *const AD_TELEMETRY_PROPERTY_VALUE_FAMILY_REFRESH_TOKEN;
extern NSString *const AD_TELEMETRY_PROPERTY_VALUE_ADFS_TOKEN;
extern NSString *const AD_TELEMETRY_PROPERTY_VALUE_BY_CODE;
extern NSString *const AD_TELEMETRY_PROPERTY_VALUE_BY_REFRESH_TOKEN;
extern NSString *const AD_TELEMETRY_PROPERTY_VALUE_SUCCEEDED;
extern NSString *const AD_TELEMETRY_PROPERTY_VALUE_FAILED;
extern NSString *const AD_TELEMETRY_PROPERTY_VALUE_CANCELLED;
extern NSString *const AD_TELEMETRY_PROPERTY_VALUE_UNKNOWN;
extern NSString *const AD_TELEMETRY_PROPERTY_VALUE_AUTHORITY_AAD;
extern NSString *const AD_TELEMETRY_PROPERTY_VALUE_AUTHORITY_ADFS;
