# Pipeline will be triggered for PR & any updates on the PR on all branches
pr:
  autoCancel: true
  branches:
    include:
    - '*'
  drafts: true

# Trigger CI for only master/release branches
trigger:
  branches:
    include:
    - master
    - release/*
    exclude:
    - '*'

pool:
  vmImage: 'macOS-11'
  timeOutInMinutes: 30

steps:
  - task: ComponentGovernanceComponentDetection@0
    inputs:
      alertWarningLevel: Low
