variables:
  - name: 'releaseVersion'
    value: null
  - name: 'repositoryName'
    value: 'AzureAD/azure-activedirectory-library-for-objc'
  - name: 'repositoryBranch'
    value: 'master'
 
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - changelog.txt

pr: none
    
resources:
  repositories:
  - repository: adalRepository
    type: github
    endpoint: 'GitHub for AzureAD and Azure-Samples (as aadidgit service)'
    name: $(repositoryName)
    ref: $(repositoryBranch)
    
jobs:
- job: 'Build_Release'
  displayName: Build ADAL framework
  pool:
    vmImage: 'macOS-11'
    timeOutInMinutes: 20

  steps:
  - checkout: adalRepository
    clean: true
    submodules: true
    fetchDepth: 1
    persistCredentials: false
    
  - task: Bash@3
    displayName: Calculate checksum | extract release version from changelog
    inputs:
      targetType: 'inline'
      script: |
        ver=$(egrep -om1 '\[((0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)\]' changelog.txt | sed -E -e "s/\[|\]//g")
        echo "##vso[task.setvariable variable=releaseVersion]${ver}"
      workingDirectory: '$(Build.SourcesDirectory)'
      failOnStderr: true
      noProfile: false
      noRc: false

  - task: Shellpp@0
    displayName: Generating release archive zips
    inputs:
      type: 'FilePath'
      scriptPath: 'ReleaseArchive.sh'
      args: '$(releaseVersion) $(Build.ArtifactStagingDirectory)'
      
  - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
    displayName: 'Generate SBOM file'
    inputs:
      BuildDropPath: '$(Build.ArtifactStagingDirectory)'
      
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)
      artifactName: Artifact
